backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

display_url: https://goodhands.co
site_url: https://goodhands-cms.netlify.com/

media_library:
  name: cloudinary
  config:
    cloud_name: goodhands
    api_key: 594195651842846
    use_transformations: false

collections:
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Index Page"
        name: "index"
        file: "index.md"
        fields:
          - {label: Meta Title, name: title, widget: string}
          - {label: Meta Description, name: description, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Layout, name: layout, widget: hidden, default: homepage}
          - label: Services
            name: services
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Desktop Image, name: desktop_image, widget: image}
              - {label: Tablet Image, name: tablet_image, widget: image}
              - {label: Mobile Image, name: mobile_image, widget: image}
              - {label: URL, name: url, widget: string}
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields:
          - {label: Layout, name: layout, widget: hidden, default: about-us}
          - {label: Meta Title, name: title, widget: string}
          - {label: Meta Description, name: description, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Surprise Me URL, name: surprise_me_url, widget: string}
          - {label: Hero Heading, name: hero_heading, widget: string}
          - {label: Client Section Heading, name: client_section_heading, widget: string}
          - {label: Client Section Text, name: client_section_text, widget: string}
          - label: Clients
            name: clients
            widget: list
            fields:
              - {label: Logo, name: logo, widget: image}
          - {label: Team Heading, name: team_heading, widget: string}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Desktop Photo, name: desktop_photo, widget: image}
              - {label: Tablet Photo, name: tablet_photo, widget: image}
              - {label: Mobile Photo, name: mobile_photo, widget: image}
              - {label: Instagram, name: instagram, widget: string}
              - {label: Twitter, name: twitter, widget: string}
              - {label: Linkedin, name: linkedin, widget: string}
          - {label: Text Section Heading, name: text_section_heading, widget: string}
          - {label: Text Section Subheading, name: text_section_subheading, widget: string}
          - {label: Text Section Content, name: text_section_content, widget: text}
      - label: "Contact Page"
        name: "contact"
        file: "contact.md"
        fields:
          - {label: Layout, name: layout, widget: string, default: contact-us}
          - {label: Meta Title, name: title, widget: string}
          - {label: Meta Description, name: description, widget: string}
  - label: "Services"
    label_singular: "Service"
    name: "services"
    folder: "_services"
    create: true
    slug: "{{seo_url}}"
    editor:
      preview: false
    fields:
      - {label: Layout, name: layout, widget: hidden, default: services}
      - {label: Meta Title, name: title, widget: string}
      - {label: Meta Description, name: description, widget: string}
      - {label: SEO URL, name: seo_url, widget: string}
      - {label: Surprise Me URL, name: surprise_me_url, widget: string}
      - {label: Hero Heading, name: hero_heading, widget: string}
      - {label: Hero Desktop Image, name: hero_desktop_image, widget: image}
      - {label: Hero Tablet Image, name: hero_tablet_image, widget: image}
      - {label: Hero Mobile Image, name: hero_mobile_image, widget: image}
      - {label: Intro Subheading, name: intro_subheading, widget: string}
      - {label: Intro Heading, name: intro_heading, widget: string}
      - {label: Intro, name: intro, widget: text}
      - label: Sections
        name: sections
        widget: list
        fields:
          - {label: Heading, name: heading, widget: string}
          - {label: Content, name: content, widget: text}
          - {label: Background, name: background, widget: select, options: ["light", "dark"]}
          - {label: Large Block Position, name: large_block_position, widget: select, options: ["left", "right"], required: false}
          - {label: Large Desktop Image, name: large_desktop_image, widget: image, required: false}
          - {label: Large Tablet Image, name: large_tablet_image, widget: image, required: false}
          - {label: Large Mobile Image, name: large_mobile_image, widget: image, required: false}
          - {label: Large Content, name: large_content, widget: text, required: false}
          - {label: Large Content Background, name: large_content_background, widget: select, options: ["light", "dark"], required: false}
          - {label: Small Image Position, name: small_image_position, widget: select, options: ["top", "bottom"], , required: false}
          - {label: Small Desktop Image, name: small_desktop_image, widget: image, required: false}
          - {label: Small Tablet Image, name: small_tablet_image, widget: image, required: false}
          - {label: Small Mobile Image, name: small_mobile_image, widget: image, required: false}
          - {label: Video Link, name: video_link, widget: string, required: false}
        
