backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

display_url: https://goodhands.co
site_url: https://goodhands-cms.netlify.com/

collections:
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Index Page"
        name: "index"
        file: "index.md"
        fields:
          - {label: Meta Title, name: title, widget: string}
          - {label: Meta Description, name: description, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Layout, name: layout, widget: hidden, default: homepage}
          - label: Services
            name: services
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Desktop Image, name: desktop_image, widget: image}
              - {label: Tablet Image, name: tablet_image, widget: image}
              - {label: Mobile Image, name: mobile_image, widget: image}
              - {label: URL, name: url, widget: string}
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Layout, name: layout, widget: hidden, default: about-us}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
      
